service: lambda-nisaba

provider:
  name: aws
  runtime: nodejs6.10
  stage: develop
  region: us-west-2

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

functions:
  v3sms:
    handler: src/api-v3_handler.sms
    description: Send code thru SMS
    events:
     - http:
         path: v3/sms
         method: post
  v3call:
    handler: src/api-v3_handler.call
    description: Send code thru phone call
    events:
     - http:
         path: v3/call
         method: post
  v3check:
    handler: src/api-v3_handler.check
    description: Verify Code
    events:
     - http:
         path: v3/sms
         method: post
  v3attestation:
    handler: src/api-v3_handler.attestation
    description: Create Phone Attestation
    events:
     - http:
         path: v3/phone
         method: post       
  
